project:
  type: website
  output-dir: docs

website:
  title: "Ixchel Ramirez - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Weekly Notes 
        menu:
          - href: weekly-notes/week-01-notes.qmd
            text: Week 1
          - href: weekly-notes/week-02-notes.qmd
            text: Week 2
          - href: weekly-notes/week-03-notes.qmd
            text: Week 3
          - href: weekly-notes/week-04-notes.qmd
            text: Week 4
          - href: weekly-notes/week-05-notes.qmd
            text: Week 5
          - href: weekly-notes/week-06-notes.qmd
            text: Week 6
          - href: weekly-notes/week-07-notes.qmd
            text: Week 7
          - href: weekly-notes/week-08-notes.qmd
            text: Week 8           
      - text: lab 
        menu:
          - href: labs/lab1/scripts/assignment1.qmd
            text: Lab 1
          - href: labs/lab_2/Ramirez_Ixchel_Assignment2.qmd
            text: Lab 2 
          - href: labs/lab3/Ixchel/Final_Appendix.qmd
            text: Midterm  
          - href: labs/slides/PrettySlides- Copy (2).qmd
            text: Slides

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
